language: c
sudo: false
dist: xenial
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex ./.travis-docker.sh
env:
  global:
  - PINS="mirage-profile:. mirage-profile-unix:. mirage-profile-xen:."
  matrix:
  - PACKAGE="mirage-profile" DISTRO="debian-stable" OCAML_VERSION="4.04"
  - PACKAGE="mirage-profile" DISTRO="debian-stable" OCAML_VERSION="4.05" PINS="mirage-profile:. lwt:git://github.com/mirage/lwt#tracing"
  - PACKAGE="mirage-profile-unix" DISTRO="debian-stable" OCAML_VERSION="4.06" PINS="mirage-profile:. mirage-profile-unix:. lwt:git://github.com/mirage/lwt#tracing" POST_INSTALL_HOOK="dune runtest"
  - PACKAGE="mirage-profile-xen" DISTRO="debian-stable" OCAML_VERSION="4.05"
  - PACKAGE="mirage-profile" DISTRO="debian-stable" OCAML_VERSION="4.05"
